### ISSUE TITLE
Is the framework's development still active?

### ISSUE THREAD

**Issue by martonlente** [kbrsh/wing#86]
Hello,

Wing is an amazing, easy to use CSS framework – truely one-of-a-kind. **However its grid system is simply broken, since the last commit, made last year in June, as described in #82.**

Do you plan fixing this in future, so that the development is still active? I don't expect 'big' updates since Wing is a simple product, but fixing its grid system seems essential.

Thanks in advance,
Márton Lente

**Comment by kbrsh** [comment]
Hey Marton,

The development of this framework is not as active as I'd like it to be because of a variety of reasons. I haven't been able to get much time to work on any of my projects because of school and sports taking up the majority of my time. I apologize for the extremely late reply and I can try addressing the issue now.

Thanks for having faith in Wing and persistently making well-formatted and helpful issues — you've done your part, and I think it's time that I do mine. I'll work on fixing some of the other issues when I have time, and I'll work on #82 right now.

**Comment by martonlente** [comment]
Hello,

Thank for the fixes, and your feedback! It's just good to hear everything is all right, and the latest Wing also works again without searching for older commits. :)

Good luck for the sports and school!

Kind regards,
Márton Lente
